services:
  - type: web
    name: university-event-management-system-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: OTP_TTL_MINUTES
        value: 10
      - key: SENDER_EMAIL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
